# Data parameters
CONTEXT_LENGTH = 60
ELIGIBILITY_CONTEXT_LENGTH = 72
HORIZON = 18
MAX_SERIES = None  # None for all available series
SERIES_VAL_RATIO = 0.2
RANDOM_SEED = 42

# Architecture parameters
HIDDEN_DIM = 128
INTERMEDIATE_DIM = 256
NUM_HEADS = 4
NUM_LAYERS = 3
DROPOUT_RATE = 0.1

# Training / Inference parameters
BATCH_SIZE = 256
PREDICT_BATCH_SIZE = 512
EPOCHS = 50
LEARNING_RATE = 3e-4
AUTOREGRESSIVE_PATIENCE = 5

# File paths
TRAIN_CSV_PATH = "./data/Monthly-train.csv"
MODEL_SAVE_PATH = f"transformer_ctx{CONTEXT_LENGTH}_h{HIDDEN_DIM}_L{NUM_LAYERS}_best.keras"